### ISSUE TITLE
NPE inside AuthenticationActivity.onResume() when webview is opened not in chrome

### ISSUE THREAD

**Issue by MattPhilpot** [auth0/Auth0.Android#130]
Hey guys, this is causing some serious issues for us...

Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.linuxacademy.linuxacademy/com.auth0.android.provider.AuthenticationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference

Caused by java.lang.NullPointerException
  |com.auth0.android.provider.AuthenticationActivity.launchAuthenticationIntent (AuthenticationActivity.java:96)
 | com.auth0.android.provider.AuthenticationActivity.onResume (AuthenticationActivity.java:74)
 | android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1277)
 | android.app.Activity.performResume (Activity.java:7088)
 | android.app.ActivityThread.performResumeActivity (ActivityThread.java:3768)
 | android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3832)
 | android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2994)
 | android.app.ActivityThread.-wrap14 (ActivityThread.java)
 | android.app.ActivityThread$H.handleMessage (ActivityThread.java:1631)
 | android.os.Handler.dispatchMessage (Handler.java:102)
 | android.os.Looper.loop (Looper.java:154)
 | android.app.ActivityThread.main (ActivityThread.java:6682)
 | java.lang.reflect.Method.invoke (Method.java)
 | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
 | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)

I don't know if it's the cause every time for us, but I know how to recreate this crash.
1) Download firefox or some other browser (firefox for sure works)
2) Set firefox as default browser
3) Open app, launch auth0 webview. Notice webview opens in different application (not in same application like a chrome webview would)
4) While webview is open, close launching application
5) Finish login in webview
6) Crash

This is the only way I've been able to reproduce this crash that we're getting. The only thing that I can think of is that all of these crashes are coming from people who aren't using chrome as their default browser, and have a ton of stuff going on in the background... so when they open the webview the launching application is closed because there isn't enough system memory. Doesn't make a ton of sense though since that would be the "most recent" application...

**Comment by lbalmaceda** [comment]
Thanks for the report 👍 Low memory case is tested [here](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/test/java/com/auth0/android/provider/AuthenticationActivityTest.java#L106) so that shouldn't be the problem. Let me see if I can reproduce it first.

**Comment by lbalmaceda** [comment]
@MattPhilpot Please test with latest version (1.11.0) as that line doesn't match the stacktrace you're sharing here. If the issue persist, I'll try to repro.

**Comment by MattPhilpot** [comment]
@lbalmaceda Here is the updated stack trace when using 1.11.0 and the steps from the first post

java.lang.RuntimeException: Unable to resume activity {.../com.auth0.android.provider.AuthenticationActivity}: 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3430)
   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3470)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
   at android.app.ActivityThread.-wrap12(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6121)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
   at com.auth0.android.provider.AuthenticationActivity.launchAuthenticationIntent(AuthenticationActivity.java:98)
   at com.auth0.android.provider.AuthenticationActivity.onResume(AuthenticationActivity.java:76)
   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
   at android.app.Activity.performResume(Activity.java:6786)
   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3407)
   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3470) 
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733) 
   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:154) 
   at android.app.ActivityThread.main(ActivityThread.java:6121) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by lbalmaceda** [comment]
@MattPhilpot The way in which Android kills an activity due to low-memory is emulated by enabling that dev setting, which is what I've tried a few minutes ago. You'll need to provide different steps as those are not valid 👍

**Comment by MattPhilpot** [comment]
Alrighty, I'll see what I can do. Thanks!
