### ISSUE TITLE
JsonParseException: credentials json is not a valid json object

### ISSUE THREAD

**Issue by gregmcpugh** [auth0/Auth0.Android#148]
When doing some edge case testing we found this crash in the Auth0 Lib.
To replicate we proxy the login API response from Auth0, and provide a malformed or empty `{}` response.
I am aware this may never happen and we can catch the crash in a try, however wanted to raise as either a known issue, or for the lib to handle and respond according.
I will try and write a PR when I get time

```E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                  Process: ***, PID: 8999
                  com.google.gson.JsonParseException: credentials json is not a valid json object
                      at com.auth0.android.request.internal.CredentialsDeserializer.deserialize(CredentialsDeserializer.java:20)
                      at com.auth0.android.request.internal.CredentialsDeserializer.deserialize(CredentialsDeserializer.java:15)
                      at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
                      at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
                      at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:75)
                      at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                      at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)```

**Comment by lbalmaceda** [comment]
So the steps to replicate would be: 
1. Try any authentication method
2. Make the response return a successful response code `200` and a body with an empty object `{}`.
3. Parser fails to translate it to `Credentials`.

Is it like that? @gregmcpugh

**Comment by gregmcpugh** [comment]
Yes @lbalmaceda 
To add info, we are proxying the https://example.eu.auth0.com/oauth/token response body.

**Comment by lbalmaceda** [comment]
I've checked with the [spec](https://tools.ietf.org/html/rfc6749#section-5.1) and the `access_token` and `token_type` are required fields of the response, so an empty JSON body is an invalid case and it's fine to handle it the way we're currently doing it.
