### ISSUE TITLE
java.lang.SecurityException in CustomTabsController

### ISSUE THREAD

**Issue by y-sharafutdinov** [auth0/Auth0.Android#162]
Hello!
I have a strange crash in the app while trying to log in via Google on Xiaomi Mi A1. Could you please help me why it can be? 
**build.gradle**
``
    implementation("com.auth0.android:lock:2.8.3") {
        exclude group: 'com.android.support'
    }
``

``
Fatal Exception: java.lang.SecurityException: Binder invocation to an incorrect interface
       at android.os.Parcel.readException(Parcel.java:1942)
       at android.os.Parcel.readException(Parcel.java:1888)
       at android.support.customtabs.ICustomTabsService$Stub$Proxy.warmup(ICustomTabsService.java:224)
       at android.support.customtabs.CustomTabsClient.warmup(CustomTabsClient.java:171)
       at com.auth0.android.provider.CustomTabsController.onCustomTabsServiceConnected(CustomTabsController.java:78)
       at android.support.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:32)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1631)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1660)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:172)
       at android.app.ActivityThread.main(ActivityThread.java:6637)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
``

**Comment by lbalmaceda** [comment]
> Binder invocation to an incorrect interface

Probably means that the expected class is different from the one received in the parcel. Try removing the "exclude group" line from the dependency in the `build.gradle` file so you use the support library required by this library and not a different version.

**Comment by lbalmaceda** [comment]
Closing due to lack of activity

**Comment by alexandrudumbravan-nutmeg** [comment]
Hello,

We seem to get this issue on version 2.7.0 of "com.auth0.android:auth0" we aren't excluding any groups from the dependencies and it seems to happen when R8 (Proguard) is enabled.

Thank you
