### ISSUE TITLE
Crash with Social login- Google

### ISSUE THREAD

**Issue by alikyo** [auth0/Auth0.Android#196]
Hi,

I am getting a crash on my pixel 2 phone (Android Pie) when trying to use google as Social login.

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $[0]
        at com.google.gson.Gson.fromJson(Gson.java:939)
        at com.google.gson.Gson.fromJson(Gson.java:994)
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
        at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:41)
        at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:17)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:75)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $[0]
        at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162)
        at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:71)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.auth0.android.util.JsonRequiredTypeAdapterFactory$1.read(JsonRequiredTypeAdapterFactory.java:28)
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:994) 
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) 
        at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:41) 
        at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:17) 
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) 
        at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260) 
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:75) 
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177) 
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

The same code is working good for facebook.

Thanks

**Comment by lbalmaceda** [comment]
The line points to the `app_metadata` deserialization: https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/request/internal/UserProfileDeserializer.java#L41

Would you mind sharing the `app_metadata` of that user? You can check that on the dashboard/users section. It's probably not a map as expected.

**Comment by alikyo** [comment]
Indeed it is an object not an array
```
{

}
```

I checked the user created with Facebook. It is the same empty app_metadata

**Comment by lbalmaceda** [comment]
User and App metadata are maps, so that's fine. There's something else here. What version of the SDK are you using and how are you using it? Sounds odd that one user works but not the user. And since it's a user profile deserialization exception, I think it's related to the profile contents. So would be nice to have that as well to debug this.

**Comment by alikyo** [comment]
Hi,

I am using the last version of the SDK

```
implementation('com.auth0.android:auth0:1.14.1') {
        exclude module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'customtabs'
    }
```

I just wrapped the calls into some RxJava

so first I have to get the credentials which is working fine for both Google and Facebook

```
private Single<Credentials> retrieveCredentialsWithGoogle(final Auth0 auth0, final Activity activity) {
        return Single.fromEmitter(new Action1<SingleEmitter<Credentials>>() {
            @Override public void call(final SingleEmitter<Credentials> singleEmitter) {

                WebAuthProvider.init(auth0)
                        .withScheme("demo")
                        .withConnection("google-oauth2")
                        .start(activity, new AuthCallback() {
                            @Override public void onFailure(@NonNull Dialog dialog) {
                                singleEmitter
                                        .onError(new AuthenticationException("Google failed to login"));
                            }

                            @Override public void onFailure(AuthenticationException exception) {
                                singleEmitter.onError(exception);
                            }

                            @Override public void onSuccess(@NonNull Credentials credentials) {
                                singleEmitter.onSuccess(credentials);
                            }
                        });
            }
        });
    }
```

Then I retrieve the UserProfile, which works for Facebook and crashes with Google
```
private Single<UserProfile> retrieveUserProfile(final Auth0 auth0, final Credentials credentials) {
        return Single.fromEmitter(new Action1<SingleEmitter<UserProfile>>() {
            @Override public void call(final SingleEmitter<UserProfile> userProfileSingleEmitter) {
                AuthenticationAPIClient authentication = new AuthenticationAPIClient(auth0);
                authentication
                        .userInfo(credentials.getAccessToken())
                        .start(new BaseCallback<UserProfile, AuthenticationException>() {
                            @Override
                            public void onSuccess(final UserProfile information) {
                                userProfileSingleEmitter.onSuccess(information);
                            }

                            @Override
                            public void onFailure(final AuthenticationException error) {
                                userProfileSingleEmitter.onError(error);
                            }
                        });
            }
        });
    }
```
The final call looks like the following

```
@Override
    public Single<Auth0UserProfile> loginWithGoogle(final Activity activity) {
        final Auth0 auth0 = new Auth0(activity);
        auth0.setOIDCConformant(true);

        return retrieveCredentialsWithGoogle(auth0, activity)
                .flatMap(new Func1<Credentials, Single<UserProfile>>() {
                    @Override
                    public Single<UserProfile> call(final Credentials credentials) {
                        return retrieveUserProfile(auth0, credentials);
                    }
                })
                .map(new Func1<UserProfile, Auth0UserProfile>() {
                    @Override
                    public Auth0UserProfile call(UserProfile userProfile) {
                        return new Auth0UserProfile(userProfile.getName(), userProfile.getEmail());
                    }
                });
    }
```

Both app_metadata and user_metadata are empty for both users

**Comment by alikyo** [comment]
This is the Json that makes the Deserializer crashes

```
{"locale":"fr","app_metadata":[{"c_Id":"12345"}],"clientID":"xDNEEbPDaCzYqVgKWKi5jfqsFk1O9e7b","updated_at":"2018-10-10T11:49:42.525Z","sub":"google-oauth2|113586286489739135455","https://myprivatedomaine.com/app_metadata":[{"c_Id":"12345"}]}
```

**Comment by lbalmaceda** [comment]
I could not reproduce this. The `app_metadata` you've pasted above is an array but it should be an object. You must be having a Rule somewhere in the middle changing the contents, I guess. Try disabling them all and checking if it still happens. Also, the user profile response should be OIDC conformant and instead there are a lot of other properties present that shouldn't be there at all.

**Comment by alikyo** [comment]
Something changed on the server configuration which fixed the issue. Thanks for your support ^^.
