### ISSUE TITLE
Issue with R8 and Proguard rules

### ISSUE THREAD

**Issue by Syex** [auth0/Auth0.Android#220]
With upgrading to Android Studio 3.3 I enabled the new R8 optimizer, which is said to work with existing ProGuard rules.
That was true for all of my project, except Auth0 had a small problem after upgrading, here's the stacktrace:

```
java.lang.TypeNotPresentException: Type com.auth0.android.result.UserIdentity not present
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:67)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76)
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70)
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:75)
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70)
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:75)
        at libcore.reflect.Types.getType(Types.java:56)
        at java.lang.Class.getGenericSuperclass(Class.java:875)
        at c.g.c.c.a.<init>(SourceFile:3)
        at c.a.a.e.a.k.<init>(SourceFile:1)
        at c.a.a.e.a.m.a(SourceFile:33)
        at c.g.c.b.a.u.a(SourceFile:15)
        at c.g.c.G.a(SourceFile:8)
        at c.a.a.e.a.i.a(SourceFile:10)
        at c.n.b.g$b.a(SourceFile:5)
        at c.n.b.a.d.run(SourceFile:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: com.auth0.android.result.UserIdentity
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:65)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76) 
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70) 
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55) 
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:75) 
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70) 
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55) 
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:75) 
        at libcore.reflect.Types.getType(Types.java:56) 
        at java.lang.Class.getGenericSuperclass(Class.java:875) 
        at c.g.c.c.a.<init>(SourceFile:3) 
        at c.a.a.e.a.k.<init>(SourceFile:1) 
        at c.a.a.e.a.m.a(SourceFile:33) 
        at c.g.c.b.a.u.a(SourceFile:15) 
        at c.g.c.G.a(SourceFile:8) 
        at c.a.a.e.a.i.a(SourceFile:10) 
        at c.n.b.g$b.a(SourceFile:5) 
        at c.n.b.a.d.run(SourceFile:3) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.auth0.android.result.UserIdentity" on path: DexPathList[[zip file "/data/app/net.grandcentrix.spitch-KupH7oV5EHk2rDm9xtRnuw==/base.apk"],nativeLibraryDirectories=[/data/app/net.grandcentrix.spitch-KupH7oV5EHk2rDm9xtRnuw==/lib/x86, /data/app/net.grandcentrix.spitch-KupH7oV5EHk2rDm9xtRnuw==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:65) 
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76) 
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70) 
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55) 
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:75) 
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70) 
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55) 
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:75) 
        at libcore.reflect.Types.getType(Types.java:56) 
        at java.lang.Class.getGenericSuperclass(Class.java:875) 
        at c.g.c.c.a.<init>(SourceFile:3) 
```

I had no Auth0 rules desfined so far. I added `-keep class com.auth0.android.result.UserIdentity` to my `proguard-rules.pro` and everything seems fine again.

I don't know if this is a R8 or Auth0 issue, however, just so you're aware this exists.

**Comment by lbalmaceda** [comment]
Thanks for reporting this. I haven't played with R8 yet and still haven't upgraded to 3.3, I rather wait for the first patch version 😄. You didn't have to define your own Proguard rules because this library "exports their own" already, though probably after reading this they'll need to be tweaked. I'll keep this open as a reminder. 
In the meantime to any encountering this issue, feel free to do _keep_ any problematic class as @Syex did.
