### ISSUE TITLE
getKeyEntryCompat crashes with RuntimeException header too long

### ISSUE THREAD

**Issue by sebaslogen** [auth0/Auth0.Android#224]
### Description

Crash on an Android 5.1.1 and 7 devices calling `SecureCredentialsManager.getCredentials`.
This happened on a production user so we can't get the data passed to the function call to reproduce locally.
The crash might have been introduced by change https://github.com/auth0/Auth0.Android/pull/203

Crash traces:
```
Fatal Exception: java.lang.RuntimeException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
       at com.android.org.conscrypt.NativeCrypto.ENGINE_load_private_key(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLEngine.getPrivateKeyById(OpenSSLEngine.java:66)
       at android.security.AndroidKeyStore.engineGetKey(AndroidKeyStore.java:86)
       at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:372)
       at java.security.KeyStore.getEntry(KeyStore.java:645)
       at com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat(CryptoUtil.java:197)
       at com.auth0.android.authentication.storage.CryptoUtil.getRSAKeyEntry(CryptoUtil.java:97)
       at com.auth0.android.authentication.storage.CryptoUtil.RSADecrypt(CryptoUtil.java:249)
       at com.auth0.android.authentication.storage.CryptoUtil.getAESKey(CryptoUtil.java:345)
       at com.auth0.android.authentication.storage.CryptoUtil.decrypt(CryptoUtil.java:383)
       at com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials(SecureCredentialsManager.java:222)
       at com.auth0.android.authentication.storage.SecureCredentialsManager.getCredentials(SecureCredentialsManager.java:189)
       at com.primephonic.app.features.authentication.AuthenticationService.getCredentials(AuthenticationService.kt:157)
       at com.primephonic.app.features.authentication.AuthenticationTokenProvider.getRawJwtToken(AuthenticationTokenProvider.kt:29)
```

### Prerequisites

[X] I have checked the documentation for this library.

[X] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[X] I have checked for related or duplicate [Issues](https://github.com/auth0/Auth0.Android/issues) and [PRs](https://github.com/auth0/Auth0.Android/pulls).

[X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

- Version of Auth0.Android used: 1.15.1
- Version of Android being used: 5.1.1 (Samsung Galaxy J5) and 7 (Samsung Galaxy J3 Prime)

### Reproduction

The app starts and tries to retrieve stored credentials (it is possible that there are none yet stored).
Expected: Credentials are retrieved in case there is any stored
Outcome: App crashes

Reproducibility: We have more than 500 users already using this version of the app in production and only one experienced the crash so reproducibility is low (but the number of users on this Android version is very low <8, so maybe is only reproducible in Android 5.1.1)

**Comment by lbalmaceda** [comment]
The class does perform many checks e.g. whether an algorithm is available or not at key creation time; so if it's not compatible with the phone it shouldn't reach that point. It might be the case that a previous version of this library was less restrictive in that sense and let the user's device use it. I can't know for sure.

If you can provide actual steps to reproduce this I'm happy to help.

**Comment by lbalmaceda** [comment]
I still wasn't able to reproduce it either. Did you continue to get this error in production?

**Comment by sebaslogen** [comment]
We haven't seen this crash in a while, so feel free to close it.

**Comment by stephen1706** [comment]
Hi, I am facing the same issue as well recently on the latest version 1.23.0. 3 devices all in Android 5

> Fatal Exception: java.lang.RuntimeException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
       at com.android.org.conscrypt.NativeCrypto.ENGINE_load_private_key(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLEngine.getPrivateKeyById(OpenSSLEngine.java:66)
       at android.security.AndroidKeyStore.engineGetKey(AndroidKeyStore.java:86)
       at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:372)
       at java.security.KeyStore.getEntry(KeyStore.java:645)
       at com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat(CryptoUtil.java:204)
       at com.auth0.android.authentication.storage.CryptoUtil.getRSAKeyEntry(CryptoUtil.java:98)
       at com.auth0.android.authentication.storage.CryptoUtil.RSADecrypt(CryptoUtil.java:259)
       at com.auth0.android.authentication.storage.CryptoUtil.getAESKey(CryptoUtil.java:356)
       at com.auth0.android.authentication.storage.CryptoUtil.decrypt(CryptoUtil.java:400)
       at com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials(SecureCredentialsManager.java:237)
       at com.auth0.android.authentication.storage.SecureCredentialsManager.getCredentials(SecureCredentialsManager.java:204)

**Comment by lbalmaceda** [comment]
@stephen1706 yes, this is covered [here](https://github.com/auth0/Auth0.Android#handling-exceptions) and you should be checking those cases to fall back to a different implementation. 

While we base this on the official Android APIs and take into consideration their availability across different versions, Android is OSS and there are devices or brands that modify the ROM, making some of these classes unavailable for this SDK to use. The only thing we can do in such cases is raising that error for the developer to decide how to handle it.

**Comment by stephen1706** [comment]
@lbalmaceda I understand that during` SecureCredentialsManager.getCredentials` it may return `isDeviceIncompatible` as a sign that the device is not compatible for `SecureCredentialsManager`.
However, is there a cleaner way to check it rather than calling `SecureCredentialsManager.getCredentials` and letting it fail first?
In addition, some devices are experiencing crash instead of getting the onFailure callback, the crash stack trace is given above.

**Comment by lbalmaceda** [comment]
>However, is there a cleaner way to check it rather than calling SecureCredentialsManager.getCredentials and letting it fail first?

That's what the `callback#onFailure` is for. There's no way around this issue as I explained. You must check what the exception is and decide how to fall back in case of an incompatible device. It's like that because you don't get that failure until you try to decrypt/encrypt the stored contents. You'd basically have to try the whole flow first to know in advance.

> In addition, some devices are experiencing crash instead of getting the onFailure callback, the crash stack trace is given above.

I understand your frustration. I tried without success to reproduce that error. When I asked for reproduction steps, none was given to me. If you have a way to trigger this failure please share it so I can look into a fix.

**Comment by stephen1706** [comment]
@lbalmaceda I cannot reproduce the error from my side as well as it only happened on certain device, but it seems it crashes every time it call `SecureCredentialsManager.getCredentials` on that problematic phones.

**Comment by lbalmaceda** [comment]
@stephen1706 "Android 5" or "Android 7" devices (OP) is a bit broad IMO. What do you suggest we do to fix this?

**Comment by stephen1706** [comment]
@lbalmaceda I suggest at CryptoUtil line 204 where the crash happened, we can catch the exception there and raise a IncompatibleDeviceException in case RuntimeException is happening
