### ISSUE TITLE
Delegation endpoint no longer supported

### ISSUE THREAD

**Issue by tomrom95** [auth0/Auth0.Android#227]
### Description
We are trying to call `AuthenicationAPIClient.renewAuth` to refresh our token, but we kept getting `An error occurred while trying to use the Refresh Token to renew the Credentials.`. After turning on HTTP logging, we found that the issue is because the `/delegation` endpoint is returning a 404.

In this [Auth0 community post](https://community.auth0.com/t/delegation-endpoint-returns-404-not-found/9333), I can see that the `/delegation` endpoint is no longer supported. Can this library be updated with the new method for refreshing tokens?

Here is an example stacktrace of the current issue:
```2019-03-18 09:23:10.225 26338-26376/: --> POST https://[REMOVED].auth0.com/delegation HTTP/1.1
2019-03-18 09:23:10.226 26338-26376/: Content-Type: application/json; charset=utf-8
2019-03-18 09:23:10.226 26338-26376/: Content-Length: 171
2019-03-18 09:23:10.226 26338-26376/: Accept-Language: en_US
2019-03-18 09:23:10.226 26338-26376/: Auth0-Client: [REMOVED]
2019-03-18 09:23:10.226 26338-26376/: {"refresh_token":"[REMOVED]","grant_type":"urn:ietf:params:oauth:grant-type:jwt-bearer","client_id":"[REMOVED]"}
2019-03-18 09:23:10.226 26338-26376/: --> END POST (171-byte body)
2019-03-18 09:23:10.266 26338-26376/: <-- HTTP/1.1 404 Not Found (40ms)
2019-03-18 09:23:10.267 26338-26376/: Date: Mon, 18 Mar 2019 16:23:11 GMT
2019-03-18 09:23:10.267 26338-26376/: Content-Type: text/plain; charset=utf-8
2019-03-18 09:23:10.267 26338-26376/: Content-Length: 9
2019-03-18 09:23:10.267 26338-26376/: Connection: keep-alive
2019-03-18 09:23:10.267 26338-26376/: X-Auth0-RequestId: d1f757c8cfb49ee48ec3
2019-03-18 09:23:10.267 26338-26376/: X-RateLimit-Limit: 1000000
2019-03-18 09:23:10.267 26338-26376/: X-RateLimit-Remaining: 999999
2019-03-18 09:23:10.267 26338-26376/: X-RateLimit-Reset: 1552926192
2019-03-18 09:23:10.267 26338-26376/: Cache-Control: private, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
2019-03-18 09:23:10.267 26338-26376/: OkHttp-Sent-Millis: 1552926190230
2019-03-18 09:23:10.267 26338-26376/: OkHttp-Received-Millis: 1552926190266
2019-03-18 09:23:10.267 26338-26376/: Not Found
2019-03-18 09:23:10.268 26338-26376/: <-- END HTTP (9-byte body)
    com.auth0.android.authentication.storage.CredentialsManagerException: An error occurred while trying to use the Refresh Token to renew the Credentials.
        at com.auth0.android.authentication.storage.CredentialsManager$1.onFailure(CredentialsManager.java:98)
        at com.auth0.android.authentication.storage.CredentialsManager$1.onFailure(CredentialsManager.java:87)
        at com.auth0.android.request.internal.BaseRequest.postOnFailure(BaseRequest.java:96)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:68)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)```

### Environment

- Version of Auth0.Android used: 15.1.1
- Version of Android being used: 28
- Additional packages that might be affecting your instance: We are also using Lock.Android 2.12.1

### Reproduction
Call `renewAuth` and notice you get a 404.

**Comment by lbalmaceda** [comment]
@tomrom95 The logs you shared are missing the actual URL being called. If you haven't removed it on purpose it should be a few lines above. In case we need to follow up this, please next time bear to share the whole log output. 👍 I'll base my response below on that you want to refresh the tokens.

Regarding Delegation, yes it was deprecated and then disabled some time ago, with the proper notifications being sent to the Auth0 users in time. I don't think new tenants can make use of it. But if you have an old tenant+application with Delegation already enabled you should still be able to use it AFAIK. If the application is new however it will be using the new pipeline for authentication (the OIDC conformant one). As explained in the javadoc of the `AuthenticationAPIClient#renewAuth` method there's a flag you need to enable in the `Auth0` instance to tell this method (and others like the log in one) which path or grant to use. This is also explained in the [README](https://github.com/auth0/Auth0.Android#oidc-conformant-mode). Please, go ahead and make that change and see if that fixes it. Your [application](https://manage.auth0.com/#/applications) should as well be marked as `OIDC conformant` in the `Settings / Advanced / OAuth` tab. 

The endpoint you will use is documented [here](https://auth0.com/docs/api/authentication#refresh-token).

**Comment by camhart** [comment]
Setting  `auth0Account.setOIDCConformant(true);` solved this for me.

**Comment by lbalmaceda** [comment]
@camhart that flag would make the method use the `/oauth/token` and the refresh token grant. https://github.com/auth0/Auth0.Android/blob/829cc322e553f6296ed86a25ff133db669b4c0b9/auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java#L729-L733. While the intent is similar (exchanging a refresh token for fresh credentials) it might not have the original behavior.

**Comment by amanzan** [comment]
@camhart thanks. I was banging my head against the wall with this issue. If /delegation endpoint is no longer supported, not sure why it is used internally while trying to renew the token...

**Comment by lbalmaceda** [comment]
While the delegation endpoints are considered legacy according to the authentication API docs, they are still available in the API and with the right client setup, you would still be able to consume them by calling the methods directly. They are not considered deprecated for this SDK. 

Since the OpenID Connect compliant endpoint to renew tokens was made available, that one must be used for OIDC enabled clients. This SDK uses a flag just like the dashboard does to tell which endpoint to call and what authentication pipeline to follow, either legacy (non-OIDC) or current (OIDC). If you're in doubt, you should always renew the tokens through that method and not using the direct ones. But that is up to you.

The java docs for the [renewAuth](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java#L774-L776) method explain which endpoint would be called on each case, depending on that flag's value. You can also find this referenced on the [Auth0](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/Auth0.java#L44-L52) class (used to instantiate the client) and very detailed on the [flag setter](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/Auth0.java#L201-L223) method. Lastly, our README explains this right at the beginning of the SDK's [usage section](https://github.com/auth0/Auth0.Android#oidc-conformant-mode). 

@amanzan you might as well have been following an outdated article or quickstart. If that's the case, do you mind sharing the link? So we can improve our guidance and prevent this from happening to the next user.

Thanks
