### ISSUE TITLE
NPE in CryptoUtil when saveCredentials 

### ISSUE THREAD

**Issue by Grzelazny** [auth0/Auth0.Android#230]
### Description
NullPointerException when save credentials, after user login produce null pointer exception, because PrivateKeyEntry in constructor have check null pointer if created object has null fields.

### Prerequisites

+ I have checked the documentation for this library https://github.com/auth0/Auth0.Android.
+ I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
+ I have checked for related or duplicate [Issues]
+ I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

+ I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.Android used:1.15.1
- Version of Android being used:26
- Additional packages that might be affecting your instance:

### Reproduction

Reproduced in user on instabug. 

Looks like storage has key, but value of this key is null, so on constructor new exception is thrown.

```
java.lang.NullPointerException: invalid null input
	 at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:559)
	 at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:526)
	 at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:477)
	 at java.security.KeyStore.getEntry(KeyStore.java:1560)
	 at com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat(CryptoUtil.java:197)
	 at com.auth0.android.authentication.storage.CryptoUtil.getRSAKeyEntry(CryptoUtil.java:97)
	 at com.auth0.android.authentication.storage.CryptoUtil.RSAEncrypt(CryptoUtil.java:297)
	 at com.auth0.android.authentication.storage.CryptoUtil.getAESKey(CryptoUtil.java:353)
	 at com.auth0.android.authentication.storage.CryptoUtil.encrypt(CryptoUtil.java:434)
	 at com.auth0.android.authentication.storage.SecureCredentialsManager.saveCredentials(SecureCredentialsManager.java:148)
	 at ch.letemps.internal.auth.Auth.onSuccess(Auth.kt:44)
	 at com.auth0.android.provider.OAuthManager$1.onSuccess(OAuthManager.java:145)
	 at com.auth0.android.provider.PKCE$1.onSuccess(PKCE.java:90)
	 at com.auth0.android.provider.PKCE$1.onSuccess(PKCE.java:87)
	 at com.auth0.android.request.internal.BaseRequest.postOnSuccess(BaseRequest.java:92)
	 at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:76)
	 at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	 at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	 at java.lang.Thread.run(Thread.java:764)
```

**Comment by Grzelazny** [comment]
On Version of Auth0.Android used:1.15.2 same issue.

**Comment by lbalmaceda** [comment]
@Grzelazny can you provide a code to reproduce this?

**Comment by neurotrackRyan** [comment]
I have a nearly identical issue. It happens randomly though, so I can't reproduce it. It happens inside `saveCredentials(credentials)` and it looks like the `getAESKey()` returns null in this line of code `SecretKey key = new SecretKeySpec(getAESKey(), ALGORITHM_AES);` in method `public byte[] encrypt(byte[] decryptedInput)`

`java.lang.IllegalArgumentException: Empty key
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
        at com.auth0.android.authentication.storage.CryptoUtil.encrypt(CryptoUtil.java:243)
        at com.auth0.android.authentication.storage.SecureCredentialsManager.saveCredentials(SecureCredentialsManager.java:146)
        at com.neurotrack.mhp.app.login.LoginActivity.finishAuthFlow(LoginActivity.kt:114)
        at com.neurotrack.mhp.app.login.LoginActivity.access$finishAuthFlow(LoginActivity.kt:23)
        at com.neurotrack.mhp.app.login.LoginActivity$promptLogin$1.onSuccess(LoginActivity.kt:82)
        at com.auth0.android.provider.OAuthManager$1.onSuccess(OAuthManager.java:145)
        at com.auth0.android.provider.PKCE$1.onSuccess(PKCE.java:90)
        at com.auth0.android.provider.PKCE$1.onSuccess(PKCE.java:87)
        at com.auth0.android.request.internal.BaseRequest.postOnSuccess(BaseRequest.java:92)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:76)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by maxbaldrighi** [comment]
Hello, I'm incurring in the same NPE @Grzelazny is facing.

- Auth0 version: 1.17.0
- Android target and compile version: 29
- Devices experiencing the problem:
  1. Motorola Moto E(4), running Android 7.1.1
  2. Samsung Galaxy J2, running Android 7.1.1

```
Fatal Exception: java.lang.NullPointerException: invalid null input
    at java.security.KeyStore$PrivateKeyEntry.<init> + 423(KeyStore.java:423)
    at java.security.KeyStoreSpi.engineGetEntry + 477(KeyStoreSpi.java:477)
    at java.security.KeyStore.getEntry + 1323(KeyStore.java:1323)
    at com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat + 197(CryptoUtil.java:197)
    at com.auth0.android.authentication.storage.CryptoUtil.getRSAKeyEntry + 97(CryptoUtil.java:97)
    at com.auth0.android.authentication.storage.CryptoUtil.RSAEncrypt + 297(CryptoUtil.java:297)
    at com.auth0.android.authentication.storage.CryptoUtil.getAESKey + 353(CryptoUtil.java:353)
    at com.auth0.android.authentication.storage.CryptoUtil.encrypt + 434(CryptoUtil.java:434)
    at com.auth0.android.authentication.storage.SecureCredentialsManager.saveCredentials + 148(SecureCredentialsManager.java:148)
    at <MY_PACKAGE>.storeCredentials + 291(AuthManager.kt:291)
    at <MY_PACKAGE>.storeCredentials$default + 259(AuthManager.kt:259)
    at <MY_PACKAGE>$doAuthAction$$inlined$apply$lambda$2.onSuccess + 175(AuthManager.kt:175)
    at com.auth0.android.provider.OAuthManager$1.onSuccess + 155(OAuthManager.java:155)
    at com.auth0.android.provider.PKCE$1.onSuccess + 90(PKCE.java:90)
    at com.auth0.android.provider.PKCE$1.onSuccess + 87(PKCE.java:87)
    at com.auth0.android.request.internal.BaseRequest.postOnSuccess + 93(BaseRequest.java:93)
    at com.auth0.android.request.internal.SimpleRequest.onResponse + 77(SimpleRequest.java:77)
    at com.squareup.okhttp.Call$AsyncCall.execute + 177(Call.java:177)
    at com.squareup.okhttp.internal.NamedRunnable.run + 33(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker + 1133(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run + 607(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run + 762(Thread.java:762)
```

In addition to this, only a Samsung Galaxy A20e running Android 9 incurred in this NPE, always while saving credentials:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.security.cert.Certificate.getType()' on a null object reference
       at java.security.KeyStore$PrivateKeyEntry.<init> + 567(KeyStore.java:567)
       at java.security.KeyStore$PrivateKeyEntry.<init> + 526(KeyStore.java:526)
       at com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat + 208(CryptoUtil.java:208)
       at com.auth0.android.authentication.storage.CryptoUtil.getRSAKeyEntry + 97(CryptoUtil.java:97)
       at com.auth0.android.authentication.storage.CryptoUtil.RSAEncrypt + 297(CryptoUtil.java:297)
       at com.auth0.android.authentication.storage.CryptoUtil.getAESKey + 353(CryptoUtil.java:353)
       at com.auth0.android.authentication.storage.CryptoUtil.encrypt + 434(CryptoUtil.java:434)
       at com.auth0.android.authentication.storage.SecureCredentialsManager.saveCredentials + 148(SecureCredentialsManager.java:148)
       at <MY_PACKAGE>.storeCredentials + 291(AuthManager.kt:291)
       at <MY_PACKAGE>.storeCredentials$default + 259(AuthManager.kt:259)
       at <MY_PACKAGE>$doAuthAction$$inlined$apply$lambda$2.onSuccess + 175(AuthManager.kt:175)
       at com.auth0.android.provider.OAuthManager$1.onSuccess + 155(OAuthManager.java:155)
       at com.auth0.android.provider.PKCE$1.onSuccess + 90(PKCE.java:90)
       at com.auth0.android.provider.PKCE$1.onSuccess + 87(PKCE.java:87)
       at com.auth0.android.request.internal.BaseRequest.postOnSuccess + 93(BaseRequest.java:93)
       at com.auth0.android.request.internal.SimpleRequest.onResponse + 77(SimpleRequest.java:77)
       at com.squareup.okhttp.Call$AsyncCall.execute + 177(Call.java:177)
       at com.squareup.okhttp.internal.NamedRunnable.run + 33(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 764(Thread.java:764)
```

We are counting a total of 3 occurrences, 1 time for each device... And so far the crash is not reproducible.
