### ISSUE TITLE
The AES Key exists but an IV was never stored. Try to encrypt something first.    

### ISSUE THREAD

**Issue by krishna-dowjones** [auth0/Auth0.Android#241]
Caused by com.xxxxx.authlib.DjCryptoUtil$MissingIVException: The AES Key exists but an IV was never stored. Try to encrypt something first.
       at com.xxxxx.authlib.DjCryptoUtil.decrypt(DjCryptoUtil.java:253)
       at com.xxxxx.authlib.DjCredentialsManager.decryptToken(DjCredentialsManager.java:163)
       at com.xxxxx.authlib.DjCredentialsManager.getCredentials(DjCredentialsManager.java:120)
       at com.xxxxx.authlib.Authenticator.getUser(Authenticator.java:199)
       at com.xxxxx.userlib.UserLibRx.getUser(UserLibRx.java:119)
       

After pushing an app update on Google Play store, the app crashes more than on 1500 devices. I have tried most of things but I could not reproduced.

**Comment by lbalmaceda** [comment]
@krishna-dowjones Please complete the issue template and provide as much details as possible. e.g. what version of the library was that? 

The `CredentialsManager` classes got a refactor some months ago. But the exceptions that could be thrown are listed in the readme https://github.com/auth0/Auth0.Android#handling-exceptions. Some are "recoverable" and some are not, but that's checkable from the exception instance itself. Depending on the error sometimes retrying the operation would fix it. I'll await for more details.
