### ISSUE TITLE
CredentialsManagerException A change on the Lock Screen security settings have deemed the encryption keys invalid and have been recreated. Any previously stored content is now lost. Please, try saving the credentials again.

### ISSUE THREAD

**Issue by shinejosephDev** [auth0/Auth0.Android#258]
### Description

Sometimes `onFailure` is invoked in `getCredentials` when the the app is in background for log time and resuming from there.
### Reproduction

Keep the app in background for sometime say 1 hr then resume. App will restart based on the memory and then `onFailure `is invoked with following exception - 
`com.auth0.android.authentication.storage.CredentialsManagerException`
`A change on the Lock Screen security settings have deemed the encryption keys invalid and have been recreated. Any previously stored content is now lost. Please, try saving the credentials again.`

But i didnt do anything with settings, bt still this comes up. This issue causes  my app to logout all of sudden.

I'm not sure this issue has anything to do with keeping app in background, but only noticed in this case.
### Environment
Using` implementation 'com.auth0.android:auth0:1.15.2'`
OnePlus 6 with android 9

**Comment by lbalmaceda** [comment]
@shinejosephDev One plus is known for modifying the OS (ROM). Is this issue still happening to you? It's hard to reproduce on our end. It might be Android locking the device after some idle time and if that counts as changing the Screen Lock security, the keys will be invalidated.

**Comment by lbalmaceda** [comment]
Closing because of inactivity

**Comment by stephen1706** [comment]
Hi @lbalmaceda, I am facing the same issue at various phone (Samsung, Xiaomi, etc) and OS level as well on production, although I cannot reproduce it on my end. I don't think it only happen to someone who is changing their screen lock security as the occurrence number is quite high
Error message returned when calling getCredentials: 

> The AES encrypted input is corrupted and cannot be recovered. Please discard it.

**Comment by stephen1706** [comment]
@lbalmaceda do you think this error will persist on certain devices? If yes, I might have to fallback to normal `CredentialsManager` permanently on this devices instead of using `SecureCredentialsManager`. What do you think?

**Comment by lbalmaceda** [comment]
@stephen1706 This error is expected and completely normal as explained previously. You can decide to retry the operation when it happens, since keys have been deleted and it will recreate them the next time you call save or get. Or you can also fallback to the non-secure option or any other storage strategy that you decide. That is also documented on the link I shared above.

**Comment by stephen1706** [comment]
@lbalmaceda today it happened to my test phone, I didn't change lock screen security, basically just reopening my app from yesterday. It happened when it call `secureCredentialsManager.getCredentials`. 
Device type: Xiaomi mi a1, this is a vanilla android OS 9 so I am wondering is there any reason for this behaviour? 
Stack trace:

> 2020-06-13 10:45:07.720 16170-16325/sg.ntucenterprise.authentication.demo D/SecureCredentialsManager: Credentials were just removed from the storage
2020-06-13 10:45:07.721 16170-16325/sg.ntucenterprise.authentication.demo W/System.err: com.auth0.android.authentication.storage.CredentialsManagerException: A change on the Lock Screen security settings have deemed the encryption keys invalid and have been recreated. Any previously stored content is now lost. Please, try saving the credentials again.
2020-06-13 10:45:07.721 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials(SecureCredentialsManager.java:245)
2020-06-13 10:45:07.721 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at com.auth0.android.authentication.storage.SecureCredentialsManager.getCredentials(SecureCredentialsManager.java:204)
...
2020-06-13 10:45:07.724 16170-16325/sg.ntucenterprise.authentication.demo W/System.err: Caused by: com.auth0.android.authentication.storage.CryptoException: The AES encrypted input is corrupted and cannot be recovered. Please discard it.
2020-06-13 10:45:07.724 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at com.auth0.android.authentication.storage.CryptoUtil.decrypt(CryptoUtil.java:436)
2020-06-13 10:45:07.724 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials(SecureCredentialsManager.java:237)
2020-06-13 10:45:07.724 16170-16325/sg.ntucenterprise.authentication.demo W/System.err: 	... 26 more
2020-06-13 10:45:07.724 16170-16325/sg.ntucenterprise.authentication.demo W/System.err: Caused by: javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
2020-06-13 10:45:07.724 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2020-06-13 10:45:07.725 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
2020-06-13 10:45:07.725 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at com.android.org.conscrypt.OpenSSLCipher$EVP_AEAD.throwAEADBadTagExceptionIfAvailable(OpenSSLCipher.java:1200)
2020-06-13 10:45:07.725 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at com.android.org.conscrypt.OpenSSLCipher$EVP_AEAD.doFinalInternal(OpenSSLCipher.java:1229)
2020-06-13 10:45:07.725 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:363)
2020-06-13 10:45:07.725 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2055)
2020-06-13 10:45:07.725 16170-16325/sg.ntucenterprise.authentication.demo W/System.err:     at com.auth0.android.authentication.storage.CryptoUtil.decrypt(CryptoUtil.java:409)
2020-06-13 10:45:07.725 16170-16325/sg.ntucenterprise.authentication.demo W/System.err: 	... 27 more

**Comment by lbalmaceda** [comment]
@stephen1706 From what I could find the error means that either the saved content or the keys changed. How that happened to your testing device, I don't know. 

The official docs mention something like this could happen in the event of a change in the lock screen settings, as explained on this [other exception class](https://developer.android.com/reference/android/security/keystore/KeyPermanentlyInvalidatedException) javadocs.

**Comment by jrzerr** [comment]
This happened to me after we just upgraded to 1.23.0 (from 1.17) to solve so many issues with token expiration date handling.  I can get this to happen on my Galaxy Tab Active2 where I have the lock screen set as a pin code.  I go into the app and delete all data, uninstall the app, start from scratch with a new build from Android Studio and it happens the very first thing the app does when it loads up.  So there should be no data sitting around that it is reading because of those pre-steps I did.  I did not get this to happen on a different tablet.  By chance I went into the Chrome settings and cleared all data and this issue resolved itself.  The error is just a really bad error message and doesn't point to the real issue at all.  Probably the step that I will end up taking is to force a logout when I see a really bad error, because I suspect if I was able to clear the webauth cookies it would have been fixed the next time I opened the app.

**Comment by AnD010** [comment]
Hi, I have a similar issue in my production app with differents users, how could  I handler it?
```
CryptoUtil.java
com.auth0.android.authentication.storage.CryptoUtil.RSADecrypt
```
![image](https://user-images.githubusercontent.com/6924755/86881735-407ef400-c0ef-11ea-9358-772f1cc32921.png)

**Comment by palicka** [comment]
I experience this quite often. It happens when there are couple of parallel network calls and token refresh is needed. First call passes but seconds ends with this exception. It has nothing to do with lock screen security
