### ISSUE TITLE
No installed browser found on Pixel device with Android 11

### ISSUE THREAD

**Issue by heliapp-it** [auth0/Auth0.Android#319]
Hi !

### Description

While implementing the Auth0 Android library, I tested it on two pixel devices (2XL - 4XL), and your library couldn't find an installed browser while Google Chrome is installed on both.

On a Motorola device (Android 10), it was able to found the Chrome app and on a Samsung tablet (Android 9), the Samsung Browser app.

Tested on Pixel 2 Android 10 and works fine.

### Environment
- Version of Auth0.Android used: 1.23.0
- Version of Android being used: Android 11

### Reproduction

Start the WebAuthProvider on a Pixel device with Chrome installed

StackTrace:

2020-07-16 11:02:15.834 695-695/XXXXXXXXXXXXXXXXXXXXXXXXXXX. E/LoginActivity: com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
        at com.auth0.android.provider.WebAuthProvider$Builder.start(WebAuthProvider.java:408)
        at com.auth0.android.provider.WebAuthProvider$Builder.start(WebAuthProvider.java:435)
        at XXXXXXXXXXXXXXXXXXXXXXXXXXX.onCreate(LoginActivity.kt:36)
        at android.app.Activity.performCreate(Activity.java:7995)
        at android.app.Activity.performCreate(Activity.java:7979)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Description: No Browser application installed to perform web authentication.
Code: a0.browser_not_available

**Comment by lbalmaceda** [comment]
The browser presence is checked with a basic action view intent and passing a URL as the data part. See [here](https://github.com/auth0/Auth0.Android/blob/af5decd4dc1cf4e39cd18c950907b2f8a65152b6/auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.java#L553). I wonder with all the privacy measures that are being lately introduced with Android if there's anything new we should be worried about. I'd need to investigate, but until the beta gets to a more stable release this is not a priority.

**Comment by KoCMoHaBTa** [comment]
Im having the exact same issue on android emulator.

![Screen Shot 2020-08-12 at 10 14 52](https://user-images.githubusercontent.com/1181346/89986126-c3621400-dc84-11ea-80f7-8d236e957524.png)
![Screen Shot 2020-08-12 at 10 15 03](https://user-images.githubusercontent.com/1181346/89986132-c65d0480-dc84-11ea-9e93-816b8dab61ba.png)
![Screen Shot 2020-08-12 at 10 15 59](https://user-images.githubusercontent.com/1181346/89986200-de348880-dc84-11ea-8ace-f3223818b0ae.png)
![Screen Shot 2020-08-12 at 10 16 10](https://user-images.githubusercontent.com/1181346/89986209-dffe4c00-dc84-11ea-8f41-694798e0a650.png)

**Comment by KoCMoHaBTa** [comment]
Found the [solution](https://developer.android.com/preview/privacy/package-visibility-use-cases#check-browser-available). In Android 11 app developers should describe the intents they would start in the new `queries` element in the manifest file.

Basically i've added this to my app's manifest file and it started to work. 

```
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
    </queries>
```

**Comment by lbalmaceda** [comment]
Thanks for sharing that @KoCMoHaBTa . [We do query](https://github.com/auth0/Auth0.Android/blob/ec931bb2e42e5a6e06448d1c9b7fd00539ca2724/auth0/src/main/java/com/auth0/android/provider/CustomTabsController.java#L175) for browser apps installed, though the code used is mostly like the official Chrome custom tabs library is doing the query.

I'll see if they are doing anything new for android 11. But I think giving a read to that entire article on opening URLs won't harm. We might be able to include this "queries" element from the library side.

**Comment by lbalmaceda** [comment]
@heliapp-it 👋  I tried to reproduce it locally this morning without success. The chrome browser opens up fine for me, and I'm able to complete the authentication. I don't have any other devices than emulators to test this in. Is there any special reproduction step that I should follow? 
Tested with `Pixel XL API 30` (emulator image freshly downloaded).
