### ISSUE TITLE
Permission were not granted

### ISSUE THREAD

**Issue by stephen1706** [auth0/Auth0.Android#449]
Hi, on samsung device using a samsung browser, I encountered a bug where the custom tab just immediately closed when the authentication process is about to start, it only happened on this device currently
This is the stack trace:

```
E/OAuthManager: Error, access denied. Check that the required Permissions are granted and that the Application has this Connection configured in Auth0 Dashboard.
W/System.err: com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
W/System.err:     at com.auth0.android.provider.OAuthManager.assertNoError(OAuthManager.java:273)
W/System.err:     at com.auth0.android.provider.OAuthManager.resume(OAuthManager.java:136)
W/System.err:     at com.auth0.android.provider.WebAuthProvider.resume(WebAuthProvider.java:531)
W/System.err:     at com.auth0.android.provider.AuthenticationActivity.deliverAuthenticationResult(AuthenticationActivity.java:129)
 W/System.err:     at com.auth0.android.provider.AuthenticationActivity.onResume(AuthenticationActivity.java:90)
```

- **Version of this library used: 1.23.1

**Comment by lbalmaceda** [comment]
@stephen1706 can you show us how you're using the SDK?

**Comment by lbalmaceda** [comment]
Closing due to inactivity
