### ISSUE TITLE
JsonIOException crash caused by SocketTimeoutException

### ISSUE THREAD

**Issue by jeffdgr8** [auth0/Auth0.Android#483]
### Describe the problem

We have a crash log from a user in production:

```
Fatal Exception: com.google.gson.JsonIOException: java.net.SocketTimeoutException: timeout
       at com.google.gson.internal.Streams.parse(Streams.java:62)
       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
       at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
       at com.auth0.android.request.internal.GsonAdapter.fromJson(GsonAdapter.kt:58)
       at com.auth0.android.request.internal.BaseRequest.execute(BaseRequest.kt:99)
       at com.auth0.android.request.internal.BaseRequest$start$1.run(BaseRequest.kt:67)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
Caused by java.net.SocketTimeoutException: timeout
       at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
       at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
       at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:382)
       at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
       at okio.RealBufferedSource.exhausted(RealBufferedSource.kt:197)
       at okio.InflaterSource.refill(InflaterSource.kt:112)
       at okio.InflaterSource.readOrInflate(InflaterSource.kt:76)
       at okio.InflaterSource.read(InflaterSource.kt:49)
       at okio.GzipSource.read(GzipSource.kt:69)
       at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
       at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
       at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
       at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
       at java.io.InputStreamReader.read(InputStreamReader.java:184)
       at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1289)
       at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1029)
       at com.google.gson.stream.JsonReader.nextString(JsonReader.java:814)
       at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702)
       at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:715)
       at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
       at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:715)
       at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
       at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
       at com.google.gson.internal.Streams.parse(Streams.java:48)
       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
       at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
       at com.auth0.android.request.internal.GsonAdapter.fromJson(GsonAdapter.kt:58)
       at com.auth0.android.request.internal.BaseRequest.execute(BaseRequest.kt:99)
       at com.auth0.android.request.internal.BaseRequest$start$1.run(BaseRequest.kt:67)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

### What was the expected behavior?

The app shouldn't crash from this network error.

### Reproduction

Seems this would happen when the login network response is successful, but times out streaming the response body to decode the JSON.

Gson internally, in `Streams.parse()` catches `IOException` and propagates as `JsonIOException`, which is not an `IOException`, but a `RuntimeException`. There's no try/catch logic to handle errors in the call to `resultAdapter.fromJson(reader)` and propagate as `Auth0Exception`:

```
...
val reader = AwareInputStreamReader(response.body, Charset.defaultCharset())
if (response.isSuccess()) {
    //2. Successful scenario. Response of type T
    val result: T = resultAdapter.fromJson(reader)
    reader.close()
    return result
}
...
```

### Environment

- **Version of this library used:** 2.2.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by lbalmaceda** [comment]
This is a good find. I left a review in the PR. Let's keep the conversation there, please.
