### ISSUE TITLE
NullPointerException UserProfileDeserializer.java:33

### ISSUE THREAD

**Issue by H-Mezri** [auth0/Auth0.Android#509]
### Describe the problem

**App crash when auth0 sdk try to parse data ->**

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:33)
       at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:17)
       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
       at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
       at com.auth0.android.request.internal.GsonAdapter.fromJson(GsonAdapter.kt:58)
       at com.auth0.android.request.internal.BaseRequest.execute(BaseRequest.kt:99)
       at com.auth0.android.request.internal.BaseRequest$start$1.run(BaseRequest.kt:67)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

### What was the expected behavior?

Catch the NullPointerException when parsing data so the app don’t crash.

### Reproduction

- When handling getProfile response. ( AuthenticationAPIClient.userInfo() )

### Environment

- **Version of this library used:**
Auth0 2.2.0

- **Version of android SDK:**
Android 6, 8, 9, 10,11

**Comment by lbalmaceda** [comment]
Looks like the UserProfile JSON that you received has a key for email_verified but the value is null. Can you double-check that, please? Also, can you share how this user was created?
Thanks

**Comment by lbalmaceda** [comment]
I couldn't reproduce this but added a quick fix in the PR referenced above.
