### ISSUE TITLE
WebAuthProvider crashes with Brave Browser with both social login and email/username login

### ISSUE THREAD

**Issue by SoJexy** [auth0/Auth0.Android#528]
### Describe the problem
When the user has `Brave Browser` as their default browser on their Android system, the `Auth0` `WebAuthProvider` browser window will crash when selecting `email` then `password`. Or any action that prompts the software keyboard twice.

### What was the expected behavior?
`WebAuthProvider` should not crash and login flow should continue as normal.

### Reproduction
- Step 1) Device or Emulator with Brave browser installed and set as the default browser
- Step 2) Launch a `WebAuthProvider` using the `Auth0` Android SDK to a predefined universal login solution
- Step 3) Click on `email` field
- Step 4) Click on `password field`
- Browser crashes

Logcat file from Android Emulator on API 30 with Google SDK installed:
```
2021-11-09 14:02:08.834 1316-1316/? I/AndroidIME: AbstractIme.onActivate():84 PasswordIme.onActivate() : EditorInfo = Package = com.brave.browser : Type = Password : Learning = Disable : Suggestion = Hide : AutoCorrection = Disable : Microphone = Hide : NoPersonalizedLearning = Disable : AutoStartVoiceInput = Disable, IncognitoMode = false
2021-11-09 14:02:08.837 1316-1316/? I/KeyboardViewHelper: KeyboardViewHelper.getView():164 Get view with height ratio:1.000000; experiment height ratio:1.000000.
2021-11-09 14:02:08.844 1316-1316/? W/TooltipLifecycleManager: TooltipLifecycleManager.dismissTooltip():130 dismissTooltip(): tooltip with id inline_suggestion_tooltip not found in tooltipManager.
2021-11-09 14:02:08.848 20389-20389/? W/System.err: android.view.InflateException: Binary XML file line #38 in com.brave.browser:layout/0_resource_name_obfuscated: Binary XML file line #6 in com.brave.browser:layout/0_resource_name_obfuscated: Error inflating class org.chromium.chrome.browser.keyboard_accessory.tab_layout_component.KeyboardAccessoryTabLayoutView
2021-11-09 14:02:08.848 20389-20389/? W/System.err: Caused by: android.view.InflateException: Binary XML file line #6 in com.brave.browser:layout/0_resource_name_obfuscated: Error inflating class org.chromium.chrome.browser.keyboard_accessory.tab_layout_component.KeyboardAccessoryTabLayoutView
2021-11-09 14:02:08.851 20389-20389/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:852)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1231)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.ViewStub.inflateViewNoAdd(ViewStub.java:272)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.view.ViewStub.inflate(ViewStub.java:305)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at fc0.b(chromium-MonochromePublic6432.aab-stable-413008924:1)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at KV0.j(chromium-MonochromePublic6432.aab-stable-413008924:8)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at lG1.b(chromium-MonochromePublic6432.aab-stable-413008924:2)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at eG1.j(chromium-MonochromePublic6432.aab-stable-413008924:6)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at v21.j(chromium-MonochromePublic6432.aab-stable-413008924:40)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at lG1.b(chromium-MonochromePublic6432.aab-stable-413008924:2)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at eG1.l(chromium-MonochromePublic6432.aab-stable-413008924:6)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at v21.j(chromium-MonochromePublic6432.aab-stable-413008924:18)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at lG1.b(chromium-MonochromePublic6432.aab-stable-413008924:2)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at eG1.l(chromium-MonochromePublic6432.aab-stable-413008924:6)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at org.chromium.chrome.browser.keyboard_accessory.ManualFillingComponentBridge.showWhenKeyboardIsVisible(chromium-MonochromePublic6432.aab-stable-413008924:6)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:335)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.os.Looper.loop(Looper.java:183)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-11-09 14:02:08.851 20389-20389/? W/System.err: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 24: TypedValue{t=0x2/d=0x7f040180 a=-1}
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at android.content.res.TypedArray.getColorStateList(TypedArray.java:597)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at A31.b(chromium-MonochromePublic6432.aab-stable-413008924:4)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at com.google.android.material.tabs.TabLayout.<init>(chromium-MonochromePublic6432.aab-stable-413008924:58)
2021-11-09 14:02:08.851 20389-20389/? W/System.err:     at org.chromium.chrome.browser.keyboard_accessory.tab_layout_component.KeyboardAccessoryTabLayoutView.<init>(chromium-MonochromePublic6432.aab-stable-413008924:1)
2021-11-09 14:02:08.851 20389-20389/? W/System.err: 	... 31 more
2021-11-09 14:02:08.854 20389-20389/? A/chromium: [FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
2021-11-09 14:02:08.994 20532-20532/? E/chromium: [1109/140208.994126:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)
    
    
    --------- beginning of crash
2021-11-09 14:02:09.003 20389-20389/? A/libc: Fatal signal 5 (SIGTRAP), code -6 (SI_TKILL) in tid 20389 (m.brave.browser), pid 20389 (m.brave.browser)
2021-11-09 14:02:09.029 20536-20536/? I/crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
2021-11-09 14:02:09.030 282-282/? I/tombstoned: received crash request for pid 20389
2021-11-09 14:02:09.031 20536-20536/? I/crash_dump64: performing dump of process 20389 (target tid = 20389)
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_arm64/emulator_arm64:11/RSR1.210722.003/7604015:user/release-keys'
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG: Revision: '0'
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG: ABI: 'arm64'
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG: Timestamp: 2021-11-09 14:02:09-0800
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG: pid: 20389, tid: 20389, name: m.brave.browser  >>> com.brave.browser <<<
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG: uid: 10169
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG: signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG: Abort message: '[FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
    '
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG:     x0  0000000000000000  x1  000000756878bfd6  x2  ffffffffffffffff  x3  ffffffffffffffff
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG:     x4  0000000000000058  x5  fefefefefefeff02  x6  fefefefefefeff02  x7  7f7f7f7f7f7f7f7f
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG:     x8  0000000000000000  x9  0000000000000000  x10 0000000000000001  x11 0000000000000000
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG:     x12 00000000ffffff80  x13 0000000000000051  x14 00328b78313efa00  x15 0000000029aaaaab
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG:     x16 000000756ec83280  x17 000000786e64685c  x18 0000007871faa000  x19 0000007fc8160528
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG:     x20 0000007fc8160538  x21 000000000000004f  x22 000000786e651e80  x23 000000756eca0000
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG:     x24 000000756eca4c68  x25 0000000000000000  x26 00000078713ca000  x27 000000756eca0000
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG:     x28 00000004000842c8  x29 0000007fc81604c0
2021-11-09 14:02:09.033 20536-20536/? A/DEBUG:     lr  000000756bbe8494  sp  0000007fc8160070  pc  000000756bbe85cc  pst 0000000060001000
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG: backtrace:
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #00 pc 00000000038245cc  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #01 pc 000000000389faa4  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #02 pc 0000000001ddb588  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #03 pc 000000000622b2e0  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #04 pc 0000000006161758  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #05 pc 000000000616151c  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #06 pc 000000000605ecd0  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #07 pc 0000000002b904e4  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #08 pc 0000000003ab8a0c  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #09 pc 0000000003abb6f4  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #10 pc 0000000003ab9a08  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #11 pc 0000000003c33218  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #12 pc 0000000003aba7f0  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #13 pc 0000000003858eec  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #14 pc 0000000003867380  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #15 pc 0000000003895a74  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #16 pc 0000000003895a28  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #17 pc 00000000038957e8  /data/app/~~C1jM0xJj56R6fiZb83rEnQ==/com.brave.browser-jMg7EemTt1YM6suSJtLyyQ==/base.apk!libmonochrome_64.so (offset 0xf45000) (BuildId: 2358d36ab4acf1fa05b8709c3bfe6b357a3bd1e7)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #18 pc 0000000000019dac  /system/lib64/libutils.so (android::Looper::pollInner(int)+916) (BuildId: d1aa3b02347f658128fc75fb371856b9)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #19 pc 00000000000199b0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: d1aa3b02347f658128fc75fb371856b9)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #20 pc 0000000000110f74  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: dc13c3ae89f2044ec9e55326de275210)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #21 pc 000000000020fadc  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+140) (BuildId: 339e94a38e629aea381d1192e0258d731e293228)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #22 pc 000000000063ec40  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+192) (BuildId: 339e94a38e629aea381d1192e0258d731e293228)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #23 pc 000000000063b6f8  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+744) (BuildId: 339e94a38e629aea381d1192e0258d731e293228)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #24 pc 00000000003fce90  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+752) (BuildId: 339e94a38e629aea381d1192e0258d731e293228)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #25 pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #26 pc 00000000001a8a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #27 pc 00000000005556f8  /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1364) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #28 pc 00000000004d4f04  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #29 pc 00000000000896f4  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+180) (BuildId: 13577ce71153c228ecf0eb73fc39f45010d487f8)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #30 pc 000000000088eed8  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136) (BuildId: 339e94a38e629aea381d1192e0258d731e293228)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #31 pc 0000000000897608  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2280) (BuildId: 339e94a38e629aea381d1192e0258d731e293228)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #32 pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #33 pc 00000000001a8a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #34 pc 0000000000554134  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #35 pc 00000000005545e8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #36 pc 0000000000438b1c  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+656) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #37 pc 0000000000099424  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: dc13c3ae89f2044ec9e55326de275210)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #38 pc 00000000000a08b0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+836) (BuildId: dc13c3ae89f2044ec9e55326de275210)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #39 pc 0000000000003580  /system/bin/app_process64 (main+1336) (BuildId: 3254c0fd94c1b04edc39169c6c635aac)
2021-11-09 14:02:09.093 20536-20536/? A/DEBUG:       #40 pc 0000000000049418  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: ac8f7173c886715a2f2fec67246e21da)
```

Current `WebAuthProvider` setup:
```
Auth0 auth0 = getAuth0();
                WebAuthProvider.login(auth0)
                        .withScheme("[scheme]")
                        .withScope("openid profile email offline_access")
                        .withAudience("https://[audience]")
                        .start(this, new com.auth0.android.callback.Callback<Credentials, AuthenticationException>() {
                            @Override
                            public void onSuccess(Credentials credentials) {
                                // Handle success
                            }

                            @Override
                            public void onFailure(@NotNull AuthenticationException e) {
                                // Handle error
                                // For this particular bug, when the app crashes it gives the following
                                // error code: "a0.authentication_canceled"
                            }
                        });
```
### Environment
SDK version 2.5.1
When attempting to access the universal login page via Brave Browser without launching through `WebAuthProvider` there is no crash.

**Comment by jimmyjames** [comment]
Hi @SoJexy, can you confirm this is still an issue with the latest version of Brave ([1.33.105](https://www.apkmirror.com/apk/brave-software/brave-browser/brave-browser-1-33-105-release/) released today)? We had a similar issue with Chrome that required an update from Chrome itself ([more details here](https://bugs.chromium.org/p/chromium/issues/detail?id=1258176&q=chrome%20crash%20password&can=2))

**Comment by SoJexy** [comment]
@jimmyjames Thanks for investing this. I've confirmed that updating to the latest version of Brave seems to resolve this issue.

**Comment by poovamraj** [comment]
We are closing this issue since it seems to have been solved. Please feel free to open it back if required.
