### ISSUE TITLE
Error unmarshalling com.auth0.android.provider.CustomTabsOptions

### ISSUE THREAD

**Issue by lucaskivi** [auth0/Auth0.Android#626]
### Describe the problem
Restoring the app after login with browser causes a `ClassNotFoundException` when unmarshalling `com.auth0.android.provider.CustomTabsOptions

Note: I can still successfully authenticate.

The exception:
```
10:50:24.187  1124-3400  Parcel                  pid-1124                             E  Class not found when unmarshalling: com.auth0.android.provider.CustomTabsOptions
                                                                                                    java.lang.ClassNotFoundException: com.auth0.android.provider.CustomTabsOptions
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at android.os.Parcel.readParcelableCreator(Parcel.java:3350)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:3284)
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:3186)
                                                                                                    	at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
                                                                                                    	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
                                                                                                    	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1196)
                                                                                                    	at android.content.Intent.getStringExtra(Intent.java:8889)
                                                                                                    	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1128)
                                                                                                    	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:894)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1710)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1560)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1512)
                                                                                                    	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1663)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1190)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1159)
                                                                                                    Caused by: java.lang.ClassNotFoundException: com.auth0.android.provider.CustomTabsOptions
                                                                                                    	at java.lang.Class.classForName(Native Method) 
                                                                                                    	at java.lang.Class.forName(Class.java:454) 
                                                                                                    	at android.os.Parcel.readParcelableCreator(Parcel.java:3350) 
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:3284) 
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:3186) 
                                                                                                    	at android.os.Parcel.readArrayMapInternal(Parcel.java:3579) 
                                                                                                    	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
                                                                                                    	at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1196) 
                                                                                                    	at android.content.Intent.getStringExtra(Intent.java:8889) 
                                                                                                    	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1128) 
                                                                                                    	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:894) 
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1710) 
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1560) 
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1512) 
                                                                                                    	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1663) 
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1190) 
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1159) 
2022-12-22 10:50:24.187  1124-3400  Bundle                  pid-1124                             W  Failed to parse Bundle, but defusing quietly
                                                                                                    android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.auth0.android.provider.CustomTabsOptions
                                                                                                    	at android.os.Parcel.readParcelableCreator(Parcel.java:3376)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:3284)
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:3186)
                                                                                                    	at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
                                                                                                    	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
                                                                                                    	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1196)
                                                                                                    	at android.content.Intent.getStringExtra(Intent.java:8889)
                                                                                                    	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1128)
                                                                                                    	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:894)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1710)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1560)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1512)
                                                                                                    	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1663)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1190)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1159)
2022-12-22 10:50:24.376 14204-14204 Bundle                  pid-14204                            W  Attempt to cast generated internal exception:
                                                                                                    java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
                                                                                                    	at android.os.BaseBundle.getInt(BaseBundle.java:1077)
                                                                                                    	at android.content.Intent.getIntExtra(Intent.java:8824)
                                                                                                    	at com.sec.android.app.sbrowser.common.utils.SBrowserIntentUtils.safeGetIntExtra(SBrowserIntentUtils.java:1)
                                                                                                    	at com.sec.android.app.sbrowser.custom_tab.CustomTabIntentDataProvider.<init>(CustomTabIntentDataProvider.java:32)
                                                                                                    	at com.sec.android.app.sbrowser.custom_tab.CustomTabActivity.onPreInflation(CustomTabActivity.java:2)
                                                                                                    	at com.sec.android.app.sbrowser.TabActivity.onCreate(TabActivity.java:4)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8198)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8182)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8512)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### What was the expected behavior?
I do not expect to see an exception.

### Reproduction

This is reproduced consistently.

* Launch the browser
* Sign in 
* Callback redirects user back to app
* Exception occurs

My method for launching the login browser instance:
```kotlin
    /**
     * Launch Auth0 login with [params] for configuration.
     */
    private suspend fun launchLoginBrowser(
        activity: Activity,
        auth0AuthenticationType: Auth0AuthenticationType,
        params: Map<String, String>,
    ): NetworkResult<Credentials> = suspendCoroutine { continuation ->
        WebAuthProvider
            .login(auth0)
            .withScheme(activity.getString(R.string.com_auth0_scheme))
            .withScope(AUTH0_SCOPE)
            .withParameters(params)
            .withConnection(auth0AuthenticationType.connection)
            .start(
                context = activity,
                callback = object : Callback<Credentials, AuthenticationException> {
                    override fun onFailure(error: AuthenticationException) = continuation.resume(error.asFailure())

                    override fun onSuccess(result: Credentials) = continuation.resume(result.asSuccess())
                },
            )
    }
```

### Environment

- **Version of this library used:**
```kotlin
    const val auth0 = "2.8.0"
    const val auth0 = "com.auth0.android:auth0:${Versions.auth0}"
```
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
This is a major app with many dependencies but I will include a few that I think could be relevant:
### Dependencies
```kotlin
    object Kotlin {
        const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.Kotlin.coroutines}"
        const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.Kotlin.coroutines}"
        const val coroutinesGuava = "org.jetbrains.kotlinx:kotlinx-coroutines-guava:${Versions.Kotlin.coroutines}"
        const val coroutinesPlayServices =
            "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${Versions.Kotlin.coroutines}"
        const val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.Kotlin.coroutines}"
        const val serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.Kotlin.serialization}"
    }
    
        object Google {
        const val daggerHiltCompiler = "com.google.dagger:hilt-compiler:${Versions.Google.daggerHilt}"
        const val daggerHiltRuntime = "com.google.dagger:hilt-android:${Versions.Google.daggerHilt}"
        const val daggerHiltTesting = "com.google.dagger:hilt-android-testing:${Versions.Google.daggerHilt}"
        const val firebaseAnalytics = "com.google.firebase:firebase-analytics-ktx"
        const val firebaseBom = "com.google.firebase:firebase-bom:${Versions.Google.firebaseBom}"
        const val firebaseCrashlytics =
            "com.google.firebase:firebase-crashlytics-gradle:${Versions.Google.firebaseCrashlytics}"
        const val firebaseCrashlyticsSdk = "com.google.firebase:firebase-crashlytics-ktx"
        const val firebasePerformance = "com.google.firebase:firebase-perf-ktx"
        const val firebasePerfPlugin = "com.google.firebase:perf-plugin:${Versions.Google.firebasePerfPlugin}"
        const val firebaseRemoteConfig = "com.google.firebase:firebase-config-ktx"
        const val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.Google.glide}"
        const val glideConcurrent = "com.github.bumptech.glide:concurrent-integration:${Versions.Google.glide}"
        const val glideRuntime = "com.github.bumptech.glide:glide:${Versions.Google.glide}"
        const val googleServices = "com.google.gms:google-services:${Versions.Google.googleServices}"
        const val mapsCompose = "com.google.maps.android:maps-compose:${Versions.Google.mapsCompose}"
        const val material = "com.google.android.material:material:${Versions.Google.material}"
        const val osslicenses = "com.google.android.gms:play-services-oss-licenses:${Versions.Google.osslicenses}"
        const val osslicensesPlugin = "com.google.android.gms:oss-licenses-plugin:${Versions.Google.osslicensesPlugin}"
        const val playServicesLocation =
            "com.google.android.gms:play-services-location:${Versions.Google.playServicesLocation}"
        const val playServicesMap = "com.google.android.gms:play-services-maps:${Versions.Google.playServicesMap}"
    }

    object AndroidX {
        const val activity = "androidx.activity:activity-ktx:${Versions.AndroidX.activity}"
        const val activityCompose = "androidx.activity:activity-compose:${Versions.AndroidX.activity}"
        const val appCompat = "androidx.appcompat:appcompat:${Versions.AndroidX.appCompat}"
        const val browser = "androidx.browser:browser:${Versions.AndroidX.browser}"
        const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.AndroidX.constraintLayout}"
        const val coordinatorLayout =
            "androidx.coordinatorlayout:coordinatorlayout:${Versions.AndroidX.coordinatorLayout}"
        const val core = "androidx.core:core-ktx:${Versions.AndroidX.core}"
        const val desugarJdkLibs = "com.android.tools:desugar_jdk_libs:${Versions.AndroidX.desugarJdkLibs}"
        const val fragment = "androidx.fragment:fragment-ktx:${Versions.AndroidX.fragment}"
        const val gradlePlugin = "com.android.tools.build:gradle:${Versions.AndroidX.gradlePlugin}"
        const val lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.AndroidX.lifecycle}"
        const val lifecycleCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.AndroidX.lifecycle}"
        const val lifecycleJava8 = "androidx.lifecycle:lifecycle-common-java8:${Versions.AndroidX.lifecycle}"
        const val lifecycleProcess = "androidx.lifecycle:lifecycle-process:${Versions.AndroidX.lifecycle}"
        const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.AndroidX.lifecycle}"
        const val lifecycleViewModelSavedState =
            "androidx.lifecycle:lifecycle-viewmodel-savedstate:${Versions.AndroidX.lifecycle}"
        const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.AndroidX.navigation}"
        const val navigationDynamicFragment =
            "androidx.navigation:navigation-dynamic-features-fragment:${Versions.AndroidX.navigation}"
        const val navigationSafeArgsPlugin =
            "androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.AndroidX.navigation}"
        const val navigationTesting = "androidx.navigation:navigation-testing:${Versions.AndroidX.navigation}"
        const val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.AndroidX.navigation}"
        const val recyclerView = "androidx.recyclerview:recyclerview:${Versions.AndroidX.recyclerView}"
        const val security = "androidx.security:security-crypto-ktx:${Versions.AndroidX.security}"
        const val splash = "androidx.core:core-splashscreen:${Versions.AndroidX.splash}"
        const val testCore = "androidx.test:core-ktx:${Versions.AndroidX.test}"
        const val workRuntime = "androidx.work:work-runtime:${Versions.AndroidX.workRuntime}"
    }
```

### Versions
```kotlin
    object Kotlin {
        const val coroutines = "1.6.3"

        // This needs to be kept in sync with the build.gradle.kts file for 'buildSrc'.
        const val kotlin = "1.7.20"
        const val kover = "0.5.1"
        const val serialization = "1.3.3"
    }

    object Google {
        const val daggerHilt = "2.43.2"
        const val firebaseBom = "31.0.1"
        const val firebaseCrashlytics = "2.9.2"
        const val firebasePerfPlugin = "1.4.1"
        const val glide = "4.13.2"
        const val googleServices = "4.3.14"
        const val mapsCompose = "2.7.2"
        const val material = "1.6.1"
        const val osslicenses = "17.0.0"
        const val osslicensesPlugin = "0.10.5"
        const val playServicesLocation = "20.0.0"
        const val playServicesMap = "18.1.0"
    }
    
    object AndroidX {
        const val activity = "1.6.0-rc01"
        const val appCompat = "1.6.0-beta01"
        const val browser = "1.4.0"
        const val constraintLayout = "2.1.4"
        const val coordinatorLayout = "1.2.0"
        const val core = "1.8.0"
        const val desugarJdkLibs = "1.1.5"
        const val fragment = "1.5.2"
        const val lifecycle = "2.5.1"

        // This needs to be kept in sync with the build.gradle.kts file for 'buildSrc'.
        const val gradlePlugin = "7.2.2"
        const val navigation = "2.5.1"
        const val recyclerView = "1.2.1"
        const val security = "1.1.0-alpha04"
        const val splash = "1.0.0"
        const val test = "1.4.0"
        const val workRuntime = "2.7.1"
    }
```

**Comment by poovamraj** [comment]
Hi @lucaskivi, Is this specific to any devices, device manufacturers or OS versions? Will it be possible to reproduce this in our sample app - https://github.com/auth0-samples/auth0-android-sample?

**Comment by poovamraj** [comment]
Can you also verify your proguard rules follow our guidelines mentioned here - https://github.com/auth0/auth0.android/blob/main/EXAMPLES.md#proguard

**Comment by poovamraj** [comment]
Hi @lucaskivi, we would like to close this issue for now but feel free to reopen it with more details. Thanks for understanding.
