### ISSUE TITLE
Android 12+ Crash - Missing Pending Intent Flag

### ISSUE THREAD

**Issue by SeanoScribd** [auth0/Auth0.Android#640]
### Describe the problem

Crash when attempting to view login redirect with Trusted Web Activity on Android 12+

Regular redirect via:

```
    WebAuthProvider.login(account)
        .withScheme("https")
        .start(context, callback)
```

works fine.

Gradle SDK levels:
```
    compileSdk 33
    minSdk 21
    targetSdk 33
```

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.auth0test, PID: 29631
    java.lang.IllegalArgumentException: com.example.auth0test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
        at android.app.PendingIntent.getActivity(PendingIntent.java:470)
        at android.app.PendingIntent.getActivity(PendingIntent.java:434)
        at androidx.browser.customtabs.CustomTabsClient.createSessionId(CustomTabsClient.java:231)
        at androidx.browser.customtabs.CustomTabsClient.newSession(CustomTabsClient.java:269)
        at com.google.androidbrowserhelper.trusted.TwaLauncher$TwaCustomTabsServiceConnection.onCustomTabsServiceConnected(TwaLauncher.java:324)
        at androidx.browser.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:57)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2188)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2221)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### What was the expected behavior?

Navigate to Trusted Web Activity

### Reproduction

1. Build test project

2. Install to device

3. Attempt to call:
```
                WebAuthProvider.login(account)
                    .withScheme("https")
                    .withTrustedWebActivity()
                    .await(requireContext())
```

### Environment
- **v2.9.0**

**Comment by SeanoScribd** [comment]
It appears to be a bug in the `AndroidX.Browser` library
https://stackoverflow.com/a/69658495

**Comment by poovamraj** [comment]
Hi @SeanoScribd thanks for the callout. We were able to reproduce the issue and updating `androidx.browser` to 1.5.0 seems to make it work. We will cut a release soon with this fix. Thanks again.
