### ISSUE TITLE
UnsupportedOperationException thrown on Chromebooks

### ISSUE THREAD

**Issue by vrozin** [auth0/Auth0.Android#710]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hey folks, 
I've gotten an `UnsupportedOperationException` thrown exclusively on Intel Gemini Lake Chromebook and Mediatek MT8183 Chromebook. 

The stack-trace is as follows:
```
Fatal Exception: java.lang.UnsupportedOperationException:
       at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:492)
       at java.security.KeyStore.getEntry(KeyStore.java:1560)
       at com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat(CryptoUtil.java:221)
       at com.auth0.android.authentication.storage.CryptoUtil.getRSAKeyEntry(CryptoUtil.java:108)
       at com.auth0.android.authentication.storage.CryptoUtil.RSADecrypt(CryptoUtil.java:272)
       at com.auth0.android.authentication.storage.CryptoUtil.getAESKey(CryptoUtil.java:372)
       at com.auth0.android.authentication.storage.CryptoUtil.decrypt(CryptoUtil.java:416)
       at com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials$lambda-3(SecureCredentialsManager.kt:467)
```
- Could you give an insight on what can be done here so the entry retrieval for API 28+ can succeed?
- Do you think, since the issue originates in Chromebooks only (so far), it's related to OS differences of `java.security.KeyStore`?

### Reproduction

Unfortunately, there's no Chromebook in sight, so couldn't replicate the issue. 

### Auth0.Android version

2.9.3

### Android version(s)

Android 11 (API 30)

**Comment by pmathew92** [comment]
Hi @vrozin , Thans you for raising this issue. Will try to investigate this once we procure a chrome book
