### ISSUE TITLE
NullPointerException in WebAuthProvider

### ISSUE THREAD

**Issue by LouisPennachio** [auth0/Auth0.Android#720]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I notice the Android Auth0 SDK sometimes throws this exception :

```
Fatal Exception: java.lang.NullPointerException:
       at com.auth0.android.provider.WebAuthProvider.failure$auth0_release(WebAuthProvider.java:149)
       at com.auth0.android.provider.AuthenticationActivity.deliverAuthenticationFailure$auth0_release(AuthenticationActivity.java:149)
       at com.auth0.android.provider.AuthenticationActivity$launchAuthenticationIntent$1.apply(AuthenticationActivity.java:149)
       at com.auth0.android.provider.AuthenticationActivity$launchAuthenticationIntent$1.apply(AuthenticationActivity.java:149)
       at com.auth0.android.provider.CustomTabsController.lambda$null$0(CustomTabsController.java:149)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

It originates from here :

```
WebAuthProvider.login(auth0)
    .withAudience(...)
    .withNonce(...)
    .withParameters(...)
    .withRedirectUri(...)
    .withScope(...)
    .await(context)
```

Impacted Android devices: Samsung, Oppo, Transsion, Vivo, Huawei
Application state: 100% foreground
Occurence: 26 times over the last 90 days

Any hint on what could cause this ?

Thanks

### Reproduction

Reproduction steps are unknown. I've tried with my own app as well as the Auth0 sample app. The crashes happen only for end-users in production.

### Auth0.Android version

2.10.2

### Android version(s)

9, 10, 11, 12, 13

**Comment by pmathew92** [comment]
Hi @LouisPennachio , Apologies for the delayed response. Are you still observing this issue on your production app? If so, were you able to reproduce this or anything that you could share that will help us to debug this further?

**Comment by pmathew92** [comment]
I am closing this issue due to inactivity for the time being . Please feel free to reopen this if you are encountering the issue again

**Comment by hayanisaid** [comment]
We are having the same issue on our production app, and we are unable to reproduce it!
